name: allstak_flutter
description: "AllStak Flutter SDK for error tracking, request telemetry, breadcrumbs, sanitization, and mobile observability."
version: 1.0.3
homepage: https://app.allstak.sa
repository: https://github.com/AllStak/allstak-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.allstak.flutter
        pluginClass: AllStakPlugin
      ios:
        pluginClass: AllStakPlugin
